In [2]:
import json
from ibm_watson import NaturalLanguageUnderstandingV1
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator
from ibm_watson.natural_language_understanding_v1 import Features, EntitiesOptions, KeywordsOptions

import pandas as pd
from pandas.io.json import json_normalize

In [3]:
authenticator = IAMAuthenticator('bkC6hyTVS4qonY34vS0d8Q5F2YY4Kz9m0fyj1cN-5VFw')

natural_language_understanding = NaturalLanguageUnderstandingV1(
    version='2019-07-12',
    authenticator=authenticator
)

natural_language_understanding.set_service_url('https://gateway.watsonplatform.net/natural-language-understanding/api/v1/analyze?version=2019-07-12')

text = """
What a sight! Anyone who visits Singspore should take some time to visit this breathtaking place. It will be a unique experience. Pls don't miss it.
"""

response = natural_language_understanding.analyze(
    text=text,
    features=Features(entities=EntitiesOptions(emotion=True, sentiment=True, limit=100000), keywords=KeywordsOptions(emotion=True, sentiment=True, limit=100000))).get_result()

print(json.dumps(response, indent=2))

{
  "usage": {
    "text_units": 1,
    "text_characters": 150,
    "features": 2
  },
  "language": "en",
  "keywords": [
    {
      "text": "unique experience",
      "sentiment": {
        "score": 0.397967,
        "mixed": "1",
        "label": "positive"
      },
      "relevance": 0.794288,
      "emotion": {
        "sadness": 0.113328,
        "joy": 0.184752,
        "fear": 0.205239,
        "disgust": 0.028168,
        "anger": 0.162816
      },
      "count": 1
    },
    {
      "text": "Singspore",
      "sentiment": {
        "score": 0.979668,
        "label": "positive"
      },
      "relevance": 0.601348,
      "emotion": {
        "sadness": 0.085382,
        "joy": 0.388905,
        "fear": 0.103358,
        "disgust": 0.14472,
        "anger": 0.070715
      },
      "count": 1
    },
    {
      "text": "breathtaking place",
      "sentiment": {
        "score": 0.900992,
        "label": "positive"
      },
      "relevance": 0.562468,
      "emotion": {
        "sadness": 0.085382,
        "joy": 0.388905,
        "fear": 0.103358,
        "disgust": 0.14472,
        "anger": 0.070715
      },
      "count": 1
    },
    {
      "text": "Pls",
      "sentiment": {
        "score": -0.637495,
        "label": "negative"
      },
      "relevance": 0.559145,
      "emotion": {
        "sadness": 0.148831,
        "joy": 0.179551,
        "fear": 0.091248,
        "disgust": 0.074744,
        "anger": 0.088473
      },
      "count": 1
    },
    {
      "text": "sight",
      "sentiment": {
        "score": 0,
        "label": "neutral"
      },
      "relevance": 0.532076,
      "emotion": {
        "sadness": 0,
        "joy": 0,
        "fear": 0,
        "disgust": 0,
        "anger": 0
      },
      "count": 1
    },
    {
      "text": "time",
      "sentiment": {
        "score": 0.979668,
        "label": "positive"
      },
      "relevance": 0.474023,
      "emotion": {
        "sadness": 0.085382,
        "joy": 0.388905,
        "fear": 0.103358,
        "disgust": 0.14472,
        "anger": 0.070715
      },
      "count": 1
    }
  ],
  "entities": [
    {
      "type": "Company",
      "text": "Singspore",
      "sentiment": {
        "score": 0.979668,
        "label": "positive"
      },
      "relevance": 0.978348,
      "emotion": {
        "sadness": 0.085382,
        "joy": 0.388905,
        "fear": 0.103358,
        "disgust": 0.14472,
        "anger": 0.070715
      },
      "count": 1,
      "confidence": 0.300372
    }
  ]
}

In [13]:
keywords_col_names = ['WEBSITE_ID', 'REVIEW_ID', 'TEXT', 'RELEVANCE', 'COUNT',
                     'SENTIMENT_SCORE', 'SENTIMENT_LABEL', 'SADNESS', 'JOY',
                     'FEAR', 'DISGUST', 'ANGER', 'MIXED_SENTIMENT']

keywords_col_names_map = {
    'text': 'TEXT', 
    'relevance': 'RELEVANCE', 
    'count': 'COUNT', 
    'sentiment.score': 'SENTIMENT_SCORE',
    'sentiment.label': 'SENTIMENT_LABEL',
    'emotion.sadness': 'SADNESS',
    'emotion.joy': 'JOY',
    'emotion.fear': 'FEAR',
    'emotion.disgust': 'DISGUST',
    'emotion.anger': 'ANGER',
    'sentiment.mixed': 'MIXED_SENTIMENT'
}



keywords_df = json_normalize(response['keywords']).rename(columns=keywords_col_names_map)
keywords_df = keywords_df[keywords_col_names[2:]]
keywords_df.insert(0, 'REVIEW_INDEX', 1234567890)
keywords_df.insert(0, 'WEBSITE_ID', 1)
keywords_df

,WEBSITE_ID,REVIEW_INDEX,TEXT,RELEVANCE,COUNT,SENTIMENT_SCORE,SENTIMENT_LABEL,SADNESS,JOY,FEAR,DISGUST,ANGER,MIXED_SENTIMENT
0,1,1234567890,unique experience,0.794288,1,0.397967,positive,0.113328,0.184752,0.205239,0.028168,0.162816,1
1,1,1234567890,Singspore,0.601348,1,0.979668,positive,0.085382,0.388905,0.103358,0.144720,0.070715,NaN
2,1,1234567890,breathtaking place,0.562468,1,0.900992,positive,0.085382,0.388905,0.103358,0.144720,0.070715,NaN
3,1,1234567890,Pls,0.559145,1,-0.637495,negative,0.148831,0.179551,0.091248,0.074744,0.088473,NaN
4,1,1234567890,sight,0.532076,1,0.000000,neutral,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
5,1,1234567890,time,0.474023,1,0.979668,positive,0.085382,0.388905,0.103358,0.144720,0.070715,NaN

In [7]:
entities_col_names = {
    'type': 'TYPE',
    'text': 'TEXT', 
    'relevance': 'RELEVANCE', 
    'count': 'COUNT',
    'confidence': 'CONFIDENCE',
    'sentiment.score': 'SENTIMENT_SCORE',
    'sentiment.label': 'SENTIMENT_LABEL',
    'emotion.sadness': 'SADNESS',
    'emotion.joy': 'JOY',
    'emotion.fear': 'FEAR',
    'emotion.disgust': 'DISGUST',
    'emotion.anger': 'ANGER',
    'sentiment.mixed': 'MIXED_SENTIMENT',
    'disambiguation.name': 'DISAMBIGUATION_NAME',
    'disambiguation.dbpedia_resource': 'DISAMBIGUATION_RESOURCE'
}

entities_df = json_normalize(response['entities']).rename(columns=entities_col_names)
entities_df.insert(0, 'REVIEW_INDEX', 1234567890)
entities_df.insert(0, 'WEBSITE_ID', 1)
entities_df

,WEBSITE_ID,REVIEW_INDEX,TYPE,TEXT,RELEVANCE,COUNT,CONFIDENCE,SENTIMENT_SCORE,SENTIMENT_LABEL,SADNESS,JOY,FEAR,DISGUST,ANGER
0,1,1234567890,Company,Singspore,0.978348,1,0.300372,0.979668,positive,0.085382,0.388905,0.103358,0.14472,0.070715